[sepal]
entry-point = "ui.ipynb"

[project]
version = "0.0.1"

[tool.commitizen]
version = "0.0.1"
update_changelog_on_bump = true
changelog_file = "CHANGELOG.md"
changelog_incremental = true
version_files = [
    "pyproject.toml:version",
]